const QUIZ = [
 {q:'¿Qué va siempre primero en cualquier bloque del guion?',o:['Un dato de ahorro en euros para llamar la atención','Una emoción o una escena mental','La presentación completa de Iberdrola y B&M','La pregunta de cierre'],ok:1,j:'Sistema 1 antes que Sistema 2: la decisión nace emocional y luego se justifica con datos. Módulo 0 y 6.'},
 {q:'El cliente dice «esto está carísimo». ¿Qué hace usted antes de rebatir?',o:['Le ofrece un descuento inmediato','Le cuelga con educación','Valida («le entiendo») y desactiva la amenaza («sin tocar nada»)','Le pide la factura sin mediar palabra'],ok:2,j:'Protocolo: validar → desactivar → reencuadrar → avanzar. Rebatir en frío sube el cortisol y mata la venta. Módulo 4.'},
 {q:'¿Cuál de estos es un cierre correcto según el guion?',o:['«¿Le interesa la propuesta?»','«¿Quiere que le llame otro día?»','«¿Le mando la información y ya me dice?»','«¿Por WhatsApp o por correo?»'],ok:3,j:'Cierre por elección A/B, nunca sí/no. El “no” no se invoca. Módulo 5.'},
 {q:'¿Cuántas veces debe sonar el nombre del cliente durante la llamada?',o:['Una sola, al saludar','Al menos tres','Siempre en cada frase','Ninguna: suena a guion'],ok:1,j:'Ley 12 (mera exposición): lo familiar vende. Tres veces, en momentos clave. Módulo 2.'},
 {q:'¿Qué comprueba SIEMPRE antes de marcar un número nuevo?',o:['Que el cliente tenga web','La Lista Robinson en IberU','La previsión del tiempo','Que el CRM esté actualizado al 100 %'],ok:1,j:'Cumplimiento primero: Robinson y consentimiento razonable. Módulo 10.'},
 {q:'¿Para qué sirve la 2ª ronda de una objeción?',o:['Para repetir el mismo argumento más alto','Para insistir hasta cinco veces más','Para ofrecer el desbloqueo (estudio gratis / detalle) cuando el cliente insiste','Para cerrar sin escuchar'],ok:2,j:'La insistencia se responde con regalo y prueba social, no con volumen. Módulo 4.'},
 {q:'Peak-End significa que el cliente recuerda sobre todo…',o:['El principio de la llamada','El dato más técnico','El pico emocional y el final','El precio final'],ok:2,j:'Por eso el cierre dispara una escena de alivio y termina limpio con su nombre. Módulo 5.'},
 {q:'¿Cuál de estos resultados cuenta como éxito de llamada?',o:['Solo el alta firmada','Facturas recibidas, cita concertada, alta o visita técnica','Que el cliente prometa pensarlo','Que no cuelgue en el primer minuto'],ok:1,j:'Cualquiera de los cuatro gana la llamada. Los compromisos pequeños también venden. Módulo 3 y 5.'},
 {q:'¿Qué NO se puede prometer jamás?',o:['El estudio de ahorro gratuito','La emergencia eléctrica 24 h','Quitar la permanencia que tenga activa','La revisión de potencias'],ok:2,j:'Ni permanencias ni quitarlas: se mira la fecha en la factura. Los otros tres son verdad verificable. Módulo 10.'},
 {q:'¿Cuándo conviene activar la capa neuro en llamada real la primera semana?',o:['Siempre, para no perder el hilo','Solo con clientes difíciles','Nunca: es de entrenamiento, no de batalla','Solo si el cliente pregunta'],ok:2,j:'Visible para entrenar, oculta para vender. En vivo, use el modo Foco. Módulo 3 y 6.'}
];