const QUIZ = [
 {q:'¿Qué va siempre primero en cualquier bloque del guion?',o:['Un dato de ahorro en euros para llamar la atención','Una emoción o una escena mental','La presentación completa de Iberdrola y B&M','El nombre de la tarifa recomendada'],ok:1,j:'Sistema 1 antes que Sistema 2: la decisión nace emocional y luego se justifica con datos. Módulos 0 y 6.'},
 {q:'El cliente dice «es que a mí me engañaron una vez». ¿Qué hace usted antes de rebatir?',o:['Le ofrece un descuento inmediato','Le cuelga con educación','Valida («le entiendo») y desactiva la amenaza («mirar no es cambiar»)','Le jura que usted es de fiar'],ok:2,j:'Con el quemado no valen juramentos: validación + verificación con pistas concretas (900 oficial, escrito antes que firma). Módulo 4 y escenario "La Desconfiada".'},
 {q:'¿Cuál de estos es un cierre correcto según el guion?',o:['«¿Le interesa la propuesta?»','«¿Quiere que le llame otro día?»','«¿Se lo mando por WhatsApp o por correo?»','«¿Sí o no?»'],ok:2,j:'Cierre por elección A/B (canal, día, hora o modalidad), jamás sí/no. Módulo 5.'},
 {q:'¿Cuántas veces debe sonar el nombre del cliente durante la llamada?',o:['Una sola, al saludar','Al menos tres','En cada frase, sin excepción','Ninguna, suena a venta'],ok:1,j:'Mínimo tres: identidad, motivo y cierre. Marca de atención personal sin abusar. Módulos 0 y 2.'},
 {q:'¿Qué comprueba SIEMPRE antes de marcar un número nuevo?',o:['Que el cliente tenga placas solares','La Lista Robinson en IberU','Que sea de mañana','Que el cliente no esté en casa'],ok:1,j:'Lista Robinson + horario legal 9:00–13:30 / 16:30–20:00 + consentimiento razonable. Si duda: no se marca. Módulo 10.'},
 {q:'¿Para qué sirve la 2ª ronda de una objeción?',o:['Para repetir el mismo argumento más alto','Para insistir hasta cinco veces más','Para ofrecer el regalo (el estudio, la comparativa) y prueba social cercana','Para colgar antes de que diga que no'],ok:2,j:'Segunda ronda = dar más, no repetir más fuerte. Y tras dos noes claros: salida elegante. Módulo 4.'},
 {q:'Peak-End significa que el cliente recuerda sobre todo…',o:['El principio de la llamada','El dato más técnico','El pico emocional y el final','Todo por igual'],ok:2,j:'Por eso se pica la emoción buena antes del cierre y se sale por arriba, incluso en un no. Módulo 5.'},
 {q:'¿Cuál de estos resultados cuenta como éxito de llamada?',o:['Solo el alta firmada','Foto de factura prometida, cita cerrada, alta o visita del técnico apuntada','Que el cliente diga «muy interesante»','Que dure más de diez minutos'],ok:1,j:'Cuatro éxitos posibles y todos suman; el resto del guion es el camino para conseguir uno. Módulo 5.'},
 {q:'El cliente tiene placas solares y paga poco. ¿Qué hace usted?',o:['Le cuelga, no hay nada que hacer','Le ofrece el alta igualmente','Le habla de excedentes, compensación y rendimiento con su misma factura','Le ofrece quitarle las placas'],ok:2,j:'El solar es un cliente técnico, no un no: batería virtual, compensación bien ajustada y visita del técnico. Objeción "solar", módulo 4.'},
 {q:'¿Cuándo conviene activar la capa neuro en llamada real la primera semana?',o:['Siempre, para no perder el hilo','Solo con clientes difíciles','En la escuela sí; en llamada real, salvo repaso previo, mejor OFF','Jamás, está prohibida'],ok:2,j:'Las etiquetas son el andamiaje: ON para aprender, OFF para conversar de verdad. Módulo 6.'}
];