const SECTIONS = [
  {id:'guia', cat:'Empezar', label:'Guía rápida', esModulo:false},
  {id:'m0', cat:'Módulos', num:'0', label:'Bienvenida', esModulo:true},
  {id:'m1', cat:'Módulos', num:'1', label:'Tour por la interfaz', esModulo:true},
  {id:'m2', cat:'Módulos', num:'2', label:'Preparar la llamada', esModulo:true},
  {id:'m3', cat:'Módulos', num:'3', label:'Ejecutar la llamada', esModulo:true},
  {id:'m4', cat:'Módulos', num:'4', label:'Objeciones', esModulo:true},
  {id:'m5', cat:'Módulos', num:'5', label:'Cierres y seguimiento', esModulo:true},
  {id:'m6', cat:'Módulos', num:'6', label:'Capa neuro', esModulo:true},
  {id:'m7', cat:'Módulos', num:'7', label:'Roleplay', esModulo:true},
  {id:'m8', cat:'Módulos', num:'8', label:'KPIs', esModulo:true},
  {id:'m9', cat:'Módulos', num:'9', label:'Editar la herramienta', esModulo:true},
  {id:'m10', cat:'Módulos', num:'10', label:'Compliance (obligatorio)', esModulo:true},
  {id:'m11', cat:'Módulos', num:'11', label:'Evaluación final', esModulo:true},
  {id:'checklist', cat:'Práctica y examen', label:'Checklist operativa', esModulo:false},
  {id:'video', cat:'Práctica y examen', label:'Guion de video-curso', esModulo:false},
  {id:'quiz', cat:'Práctica y examen', label:'Quiz de evaluación', esModulo:false},
  {id:'casos', cat:'Práctica y examen', label:'Casos prácticos', esModulo:false},
  {id:'rutas', cat:'Referencias', label:'Rutas por rol', esModulo:false},
  {id:'faq', cat:'Referencias', label:'FAQ', esModulo:false},
  {id:'sesion', cat:'Referencias', label:'Sesión presencial 90’', esModulo:false},
  {id:'config', cat:'Referencias', label:'Configuración y mantenimiento', esModulo:false}
];