const VIDEOS = [
 {t:'V0 · Bienvenida (45 s)',planos:['Plano medio, oficina Sagunto','Inserto: la herramienta abierta','Rótulo: los 3 principios'],
  loc:'Buenos días. Esto es el guion residencial con el que va a llamar desde hoy, y le cuento lo esencial en menos de un minuto. No es un texto para recitar: es el mapa de una conversación de casa. Emoción primero, cierre por elección, compliance siempre.'},
 {t:'V1 · La interfaz (60 s)',planos:['Pantalla completa, zoom a cada zona','Subtítulos con nombres de elementos'],
  loc:'Arriba, la cabecera: capa neuro para ver los hilos, foco para agrandar el discurso sin perder el árbol, datos de la llamada, limpiar y reiniciar. Debajo, el progreso de nueve fases. Izquierda, el árbol de decisiones; derecha, siete pestañas. En la llamada vivirá en la primera.'},
 {t:'V2 · Preparar la llamada (50 s)',planos:['Inserto modal rellenándose','Recuadro: tabla de fuentes'],
  loc:'Antes de marcar: Lista Robinson, horario legal, consentimiento. Después el modal: nombre, tipo de vivienda, ciudad… el guion se personaliza solo. Y recuerde: los datos viven aquí dentro; con el botón limpiar, fuera. Privacidad real.'},
 {t:'V3 · Ejecutar la llamada (55 s)',planos:['Video-lamada simulada a cámara lenta','Recuadro: el ciclo'],
  loc:'Leer un párrafo, escuchar, pulsar, repetir. Tras cada pregunta, silencio. Si se equivoca, flecha volver. Si el guion suena a conversación, va bien; si suena a lectura, está leyendo demasiado de una vez.'},
 {t:'V4 · Objeciones (75 s)',planos:['Rótulo de los 4 pasos','Roleplay en pantalla dividida'],
  loc:'Validar, desactivar, reencuadrar, avanzar. «Estoy contento»: me alegro, no se la desmonto, pregunte por el número. La segunda ronda lleva regalo: el estudio y la comparativa. Dos noes claros, salida elegante.'},
 {t:'V5 · Cierres y seguimiento (60 s)',planos:['Los cuatro cierres en rótulo','Inserto WhatsApp <5 min'],
  loc:'Cierre siempre por elección: canal, día, hora, modalidad. Cuatro éxitos: cita, foto, alta, técnico. Y la última impresión es la que se lleva: salga por arriba, siempre. WhatsApp en menos de cinco minutos, cadencia con novedad.'},
 {t:'V6 · La capa neuro (50 s)',planos:['Las etiquetas aparecen sobre el guion','Recuadro de las 8 leyes'],
  loc:'Las etiquetas en mayúsculas le dicen qué ley está usando. Pérdida actual, Zeigarnik, prueba social, elección doble, Peak-End… ON en la escuela, OFF en la cancha.'},
 {t:'V7 · Roleplay (40 s)',planos:['Simulador en pantalla','Feedback de aciertos y fallos'],
  loc:'El simulador ensaya la decisión: el cliente habla, usted elige y el feedback le cuenta la ley. El compañero ensaya el oído. Dos roleplays completos antes de la llamada real.'},
 {t:'V8 · KPIs (45 s)',planos:['Pestaña KPIs rellenándose','Gráfica de las cuatro tasas'],
  loc:'Cuatro números al día: llamadas, contactos, estudios citados, altas. La herramienta calcula las tasas. Los lunes, foto y a la reunión: es diagnóstico, no control.'},
 {t:'V9 · Editar la herramienta (40 s)',planos:['Editor de texto con el HTML','Rótulo: copia + filtro 🇪🇸'],
  loc:'El contenido vive en el script final del HTML. Edite sobre copia, pase toda frase nueva por el filtro idiomático del glosario y la batería de tests. El responsable coordina la versión oficial.'},
 {t:'V10 · Compliance (55 s)',planos:['Las dos barreras en pantalla','Recuadro: prohibidos'],
  loc:'Lista Robinson y horario legal: las dos barreras. Verdades verificables: el estudio gratis, el 900 oficial. Prohibido prometer quitar permanencias o dar precios sin factura. Datos mínimos, limpieza al final. La venta legal es la única que cuenta.'}
];